config/routes.rb
Rails.application.routes.draw do
  devise_for :end_users
  
  root to:'homes#top'
  get 'about', to:'homes#about'
  get 'info', to:'homes#info'
  
  resources:genre,only:[:index,:create,:edit,:update,:destroy]
  resources:type,only:[:index,:create,:edit,:update,:destroy]
  resources:record
  resources:food
  resources:pet
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/end_user.rb
class EndUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :records, dependent: :destroy
  has_many :pets, dependent: :destroy
  has_many :foods, dependent: :destroy
  has_many :genres, dependent: :destroy
  has_many :types, dependent: :destroy
 
end

app/models/food.rb
class Food < ApplicationRecord
  belongs_to :end_user,optional: true
  belongs_to :genres,optional: true
  belongs_to :types,optional: true
  
  has_many :records, dependent: :destroy
  has_many :pets, through: :records
  
  # has_many :genres, through: :food_genres, dependent: :destroy
  has_one_attached :food_image
  
  def get_food_image(width, height)
   unless food_image.attached?
    file_path = Rails.root.join('app/assets/images/no_image.jpeg')
    food_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
   end
    food_image.variant(resize: "#{width}x#{height}").processed
  end
   
  def previous
   Food.where("id < ?", self.id).order("id DESC").first
  end
  def next
   Food.where("id > ?", self.id).order("id ASC").first
  end
  
  # def genre_id
  #  genre_id ? genre_id : 'no name'
  # end
  
   validates :name, presence: true
   validates :type_id, presence: true
   validates :genre_id, presence: true

end

app/controllers/food_controller.rb
class FoodController < ApplicationController
  def new
   @food = Food.new
   
   # collection_select用
   @types = current_end_user.types
   @genres = current_end_user.genres
   
   # # モーダル用
   @genre = Genre.new
   @type = Type.new
  end
 
 def create
   @food = Food.new(food_params)
   @types = current_end_user.types
   @genres = current_end_user.genres
   @food.end_user_id = current_end_user.id
   if @food.save
    redirect_to food_index_path
   else
     render:new
   end
   
 end

  def index
   # binding.pry
   @foods = Food.all
   @foods = current_end_user.foods
  end

  def show
   @food = Food.find(params[:id])
   @type = Type.find(@food.type_id)
   @genre = Genre.find(@food.genre_id)
   # # if @genre.present?
   #  @genre = Genre.find(@food.genre_id)
   # else
   #  @genre = []
   # end
  end

  def edit
   @food = Food.find(params[:id])
   @types = current_end_user.types
   @genres = current_end_user.genres
  end
  
  def update
   @food = Food.find(params[:id])
   if @food.update(food_params)
    redirect_to food_path(@food.id)
   else
    render:edit
   end
  end
  
  def destroy
   @food = Food.find(params[:id])
   @food.destroy
   redirect_to food_index_path
  end
  
  private
  # ストロングパラメータ
  def food_params
    params.require(:food).permit(:type_id, :name,:memo,:food_image, :genre_id)
  end
  
end

app/helpers/food_helper.rb
module FoodHelper
end

app/views/food/edit.html.erb
<%= form_with model: @food do |f| %>

 <%= render 'shared/errors', model: f.object %>
 
 <div class="form-group">
  <%= f.label :フード画像 %>
  <%= f.file_field :food_image,accept:"image/*" %>
 </div>
 
 <div class="form-group">
  <%= f.label :フードの名前 %>
  <%= f.text_field :name %>
 </div>
 
 <div class="form-group">
  <%= f.label :genre_id,'ジャンル' %>
  <%= f.collection_select :genre_id, @genres, :id, :name, options = { include_blank: "選択してください" } %>
 </div>
 
 <div class="form-group">
  <%= f.label :type_id,'フードタイプ' %>
  <%= f.collection_select :type_id, @types, :id, :name, options = { include_blank: "選択してください" } %>
 </div>
 
 <div class="form-group">
  <%= f.label :メモ %>
  <%= f.text_area :memo %>
 </div>
 
 <%= f.submit '変更を保存する', class:"btn btn-info mb-3" %>
 <%= link_to "削除", food_path(@food.id), method: :delete, 
 "data-confirm" => "これまでのデータが全て削除されます。本当に削除しますか？",class:"btn btn-danger mb-3" %>

 
<% end %>

app/views/food/index.html.erb
<div class = "row">
 <% @foods.each do |food|%>
 <div class="mx-1 px-3 my-1">
  <%= link_to food_path(food.id) do %>
  <div>
    <%= image_tag food.get_food_image(150,150) %>
  </div>
   <div class = "text-center py-3"><span class = "sticky"><%= food.name %></span></div>
   <% end %>
  </div>
 <% end %>
</div>

<div class = "fixed_btn">
 <%= link_to new_food_path, class:"btn btn-warning" do %>
  <i class="fas fa-bone"></i>
  フードを追加する
 <% end %>
</div>

app/views/food/new.html.erb
<div class ="title mb-3 h6">
 <span class = "border rounded border-dark py-2 px-2 bg-light">
  フードの情報を入力して下さい
 </span>
</div>

<%= form_with model: @food, url:'/food', method: :post, local: true do |f| %>

 <%= render 'shared/errors', model: f.object %>
 
 <div class="form-group pt-3">
  <%= f.label :フード画像 %>
  <%= f.file_field :food_image,accept:"image/*" %>
 </div>
 
 <div class="form-group">
  <%= f.label :フードの名前 %>
  <%= f.text_field :name %>
 </div>
 
 <div class="form-group">
  <%= f.label :genre_id,'ジャンル' %>
  <%= f.collection_select :genre_id, @genres, :id, :name, options = { include_blank: "選択してください" } %>
  <button type="button" class="btn btn-sm btn-success ml-3" data-toggle="modal" 
                data-target="#genreModal" data-whatever="@genre">ジャンルを追加</button>
 
 </div>
 
 <div class="form-group">
  <%= f.label :type_id,'フードタイプ' %>
  <%= f.collection_select :type_id, @types, :id, :name, options = { include_blank: "選択してください" } %>
  <button type="button" class="btn btn-sm btn-success ml-3" data-toggle="modal" 
                           data-target="#typeModal" data-whatever="@type">タイプを追加</button>
 
 </div>
 
 <div class="form-group">
  <%= f.label :メモ %>
  <%= f.text_area :memo %>
 </div>
 
 <%= f.submit '登録する',class:"btn btn-info mb-3" %>
 
<% end %>

<!--ジャンルモーダル用-->
<div class="modal fade" id="genreModal" tabindex="-1" aria-labelledby="exampleModalLabel" 
    aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-body mt-3" id="modal_genre">
       <%= render 'shared/modal_genre', genre: @genre %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">戻る</button>
      </div>
    </div>
  </div>
</div>

<!--タイプモーダル用-->
<div class="modal fade" id="typeModal" tabindex="-1" aria-labelledby="exampleModalLabel"
   aria-hidden="true">
 <div class="modal-dialog">
  <div class="modal-content">
   <div class="modal-body mt-3" id="modal_type">
    <%= render 'shared/modal_type', type: @type %>
   </div>
   <div class="modal-footer">
    <button type="button" class="btn btn-secondary" data-dismiss="modal">戻る</button>
   </div>
  </div>
 </div>
</div>


<%#= f.collection_check_boxes(:genre_ids, Genre.all, :id, :name) do |genre| %>
 <!--           <div class='form-group'>-->
 <!--               <%#= genre.label class: 'form-check-label' do %>-->
 <!--                   <%#= genre.check_box class: 'form-check-input' %>-->
 <!--                   <%#= genre.text %>-->
 <!--               <#% end %>-->
 <!--           </div>-->
 <!--<#% end %>-->

app/views/food/show.html.erb
<div class = "row">
 <div class = "col-md-6 text-center">
  <%= image_tag @food.get_food_image(300,300) %>
 </div>
 <div class = "col-md-6">
  <div class = "food_info py-3 px-3 mt-3">
   <u><div class ="h2 pb-3"><%= @food.name %></div></u>
   
   
   <div class ="h4 pb-2">タイプ：<%= @type.name %></div>
  
  
   <div class ="h4 pb-2">ジャンル：<%= @genre.name %></div>

   <div class ="h4 pb-2">メモ：<%= @food.memo %></div>
  </div>
 </div>
</div>

<div class="d-flex justify-content-between">
 <div>
  <% if @food.previous.present? %>
   <%= link_to food_path(@food.previous), class:"text-muted h1" do %>
    <i class="fas fa-caret-left"></i>
   <% end %>
  <% end %>
 </div>

 <div>
  <% if @food.next.present? %>
   <%= link_to food_path(@food.next), class:"text-muted h1" do %>
    <i class="fas fa-caret-right"></i>
   <% end %>
  <% end %>
 </div>
</div>

 <div class = "my-3 text-center">
  <%= link_to "フードを編集する", edit_food_path(@food.id), class:"btn btn-success" %>
  <%= link_to "フード一覧に戻る", food_index_path, class:"btn btn-secondary" %>
 </div>