config/routes.rb
Rails.application.routes.draw do
  devise_for :end_users
  
  root to:'homes#top'
  get 'about', to:'homes#about'
  get 'info', to:'homes#info'
  
  resources:genre,only:[:index,:create,:edit,:update,:destroy]
  resources:type,only:[:index,:create,:edit,:update,:destroy]
  resources:record
  resources:food
  resources:pet
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/record.rb
class Record < ApplicationRecord
  belongs_to :end_user,optional: true
  belongs_to :food, optional: true
  belongs_to :pet, optional: true
  
  validates :pet_id, presence: true
  validates :food_id, presence: true
  validates :amount, presence: true

  
end

app/controllers/record_controller.rb
class RecordController < ApplicationController
  def new
   @record = Record.new
   @pets = current_end_user.pets
   @foods = current_end_user.foods
  end
  
  def create
   @record = Record.new(record_params)
   @record.end_user_id = current_end_user.id
   if @record.save
    redirect_to record_index_path
   else
    render:new
   end
  end

 # def show
 #   @record = Record.find(params[:id])
 # end

  def index
   # binding.pry
   @records = Record.all
   # @records = Record.order(created_at: :desc)
   @records = current_end_user.records
  end

  def edit
   @record = Record.find(params[:id])
  end
  
  def update
   @record = Record.find(params[:id])
   if @record.update(record_params)
     redirect_to record_index_path
   else
    render:edit
   end
   
  end
  
  def destroy
   @record = Record.find(params[:id])
   @record.destroy
   redirect_to record_index_path
  end
  
  private
  
  def record_params
    params.require(:record).permit(:amount,:memo,:pet_id,:food_id)
    # ,:pet_name,:food_name
  end
  
end

app/helpers/record_helper.rb
module RecordHelper
end

app/views/record/edit.html.erb
<%= form_with model: @record do |f| %>

 <%= render 'shared/errors', model: f.object %>

 <div class="form-group">
  <%= f.label :うちの子の名前 %>
  <%= f.collection_select :pet_id, Pet.all, :id, :name, options = { include_blank: "選択してください" } %>
 </div>
 
 <div class="form-group">
  <%= f.label :フード名 %>
  <%= f.collection_select :food_id, Food.all, :id, :name, options = { include_blank: "選択してください" } %>
 </div>
 
 <div class="form-group">
  <%= f.label :摂取量 %>
  <%= f.select :amount,[["完食","完食"], ["半分","半分"], ["全部残した","全部残した"]], include_blank: "選択して下さい" %>
 </div>
 
 <div class="form-group">
  <%= f.label :メモ %>
  <%= f.text_area :memo %>
 </div>
 
  <%= f.submit '記録を更新する', class:"btn btn-info mb-3" %>
  <%= link_to "削除",record_path(@record.id),method: :delete,class:"btn btn-danger mb-3" %>
 
<% end %>

<%= pie_chart Record.group(:amount).sum(:food_id) %>

app/views/record/index.html.erb
<%= link_to new_record_path, class:"btn btn-warning btn-lg btn-block" do %>
 <i class="fas fa-pen"></i>
 記録する
 <i class="fas fa-pen"></i>
<% end %>

<!--<= pie_chart Food.group(:name).count %>-->
<div class="table-responsive">
 <table class="table table-light table-striped mt-3">
 
<% @records.each do |record| %>
  <tr>
   <th colspan = "5" ><%= record.created_at.strftime('%Y/%m/%d %H:%M') %></th>
  </tr>
  
  <tr>
   <td><%= record.pet.name %></td>
   <td><%= record.food.name %></td>
   <td><%= record.amount %></td>
   <td><%= record.memo %></td>
   <td>
    <%= link_to edit_record_path(record) do %>
    <i class="fas fa-edit"></i>
    <% end %>
    <%#= link_to record_path(@record) %>
   </td>
  </tr>
 <% end %>

 </table>
</div>



<!--<= link_to 'New Product', new_product_path %>-->

app/views/record/new.html.erb
<%= form_with model: @record, url:'/record', method: :post do |f| %>

 <%= render 'shared/errors', model: f.object %>

 <div class="form-group">
  <%= f.label :うちの子の名前 %>
  <%= f.collection_select :pet_id, @pets, :id, :name, options = { include_blank: "選択してください" } %>
  <!--<= f.select :pet_id, options_from_collection_for_select(Pet.all, :id, :name), options = { include_blank: "選択してください" } %>-->

 </div>
 
 <div class="form-group">
  <%= f.label :フード名 %>
  <%= f.collection_select :food_id, @foods, :id, :name, options = { include_blank: "選択してください" } %>
 </div>
 
 <div class="form-group">
  <%= f.label :摂取量 %>
  <%= f.select :amount,[["完食","完食"], ["半分","半分"], ["全部残した","全部残した"]], include_blank: "選択して下さい" %>
 </div>
 
 <div class="form-group">
  <%= f.label :メモ %>
  <%= f.text_area :memo %>
 </div>
 
  <%= f.submit '記録する',class:"btn btn-info mb-3" %>
 
<% end %>

app/views/record/show.html.erb
<div class = "title">
 <h3><strong>記録詳細</strong></h3>
</div>

<%= pie_chart Record.group(:food_id).count %>

<%= @record.pet.name %>
<%= @record.food.name %>
<%= @record.amount %>
<%= @record.memo %>

<%= link_to "記録一覧に戻る",record_index_path, class:"btn btn-secondary" %>
<%= link_to "記録を編集する",edit_record_path(@record), class:"btn btn-primary" %>