config/routes.rb
Rails.application.routes.draw do
  devise_for :end_users
  
  root to:'homes#top'
  get 'about', to:'homes#about'
  get 'info', to:'homes#info'
  
  resources:genre,only:[:index,:create,:edit,:update,:destroy]
  resources:type,only:[:index,:create,:edit,:update,:destroy]
  resources:record
  resources:food
  resources:pet
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
  
  def about
  end
  
  def info
  end
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/homes/about.html.erb
<div class = "bg-light my-3 py-3">

 <div class = "mx-3">
  <table class = "table" >
   <tr>
    <td>
     <%= link_to genre_index_path, class:"text-reset" do %>
      フードジャンル編集
      <span class = "text-right"><i class="fas fa-angle-right"></i></span>
     <% end %>
    </td>
   </tr>
   <tr>
    <td>
     <%= link_to type_index_path, class:"text-reset" do %>
      フードタイプ編集
      <span class = "text-right"><i class="fas fa-angle-right"></i></span>
     <% end %>
    </td>
   </tr>
   <tr>
    <td>
     <%= link_to info_path, class:"text-reset" do %>
      使い方
      <span class = "text-right"><i class="fas fa-angle-right"></i></span>
     <% end %>
    </td>
   </tr>
   <tr><td></td></tr>
  </table>
 </div>

</div>

app/views/homes/top.html.erb
<div id="container">
 <div id="theTarget">
  <div class="image1"></div>
  <div class="image2"></div>
  <div class="image3"></div>
 </div>
</div>

<div class= "hiddenA">
<div class = "text-center shadow bg-light mb-3">
 <div class = "line">
   <span class = "px-1"><i class="fas fa-home"></i></span><span class = "px-1"><i class="fas fa-dog"></i></span><span class = "px-1"><i class="fas fa-cat"></i></span><span class = "px-1"><i class="fas fa-bone"></i></span>
   <span class = "px-1"><i class="fas fa-home"></i></span><span class = "px-1"><i class="fas fa-dog"></i></span><span class = "px-1"><i class="fas fa-cat"></i></span><span class = "px-1"><i class="fas fa-bone"></i></span>
   <span class = "px-1"><i class="fas fa-home"></i></span><span class = "px-1"><i class="fas fa-dog"></i></span><span class = "px-1"><i class="fas fa-cat"></i></span><span class = "px-1"><i class="fas fa-bone"></i></span>
   <span class = "px-1"><i class="fas fa-home"></i></span><span class = "px-1"><i class="fas fa-dog"></i></span><span class = "px-1"><i class="fas fa-cat"></i></span><span class = "px-1"><i class="fas fa-bone"></i></span>
   <span class = "px-1"><i class="fas fa-home"></i></span><span class = "px-1"><i class="fas fa-dog"></i></span><span class = "px-1"><i class="fas fa-cat"></i></span><span class = "px-1"><i class="fas fa-bone"></i></span>
   <span class = "px-1"><i class="fas fa-home"></i></span><span class = "px-1"><i class="fas fa-dog"></i></span><span class = "px-1"><i class="fas fa-cat"></i></span><span class = "px-1"><i class="fas fa-bone"></i></span>
   <span class = "px-1"><i class="fas fa-home"></i></span><span class = "px-1"><i class="fas fa-dog"></i></span><span class = "px-1"><i class="fas fa-cat"></i></span><span class = "px-1"><i class="fas fa-bone"></i></span>
 </div>
  <br><br><br>
 <div class = "pb-3">「昨日ウチの子何食べたっけ？」</div>
 <div class = "textb pb-3">慌ただしい毎日の中でも、<br>大切なペットの食事管理をしてあげたい。</div>
 そんなあなたのための「ウチの子」です。
 <br><br><br>
 <div class = "line">
   <span class = "px-1"><i class="fas fa-home"></i></span><span class = "px-1"><i class="fas fa-dog"></i></span><span class = "px-1"><i class="fas fa-cat"></i></span><span class = "px-1"><i class="fas fa-bone"></i></span>
   <span class = "px-1"><i class="fas fa-home"></i></span><span class = "px-1"><i class="fas fa-dog"></i></span><span class = "px-1"><i class="fas fa-cat"></i></span><span class = "px-1"><i class="fas fa-bone"></i></span>
   <span class = "px-1"><i class="fas fa-home"></i></span><span class = "px-1"><i class="fas fa-dog"></i></span><span class = "px-1"><i class="fas fa-cat"></i></span><span class = "px-1"><i class="fas fa-bone"></i></span>
   <span class = "px-1"><i class="fas fa-home"></i></span><span class = "px-1"><i class="fas fa-dog"></i></span><span class = "px-1"><i class="fas fa-cat"></i></span><span class = "px-1"><i class="fas fa-bone"></i></span>
   <span class = "px-1"><i class="fas fa-home"></i></span><span class = "px-1"><i class="fas fa-dog"></i></span><span class = "px-1"><i class="fas fa-cat"></i></span><span class = "px-1"><i class="fas fa-bone"></i></span>
   <span class = "px-1"><i class="fas fa-home"></i></span><span class = "px-1"><i class="fas fa-dog"></i></span><span class = "px-1"><i class="fas fa-cat"></i></span><span class = "px-1"><i class="fas fa-bone"></i></span>
   <span class = "px-1"><i class="fas fa-home"></i></span><span class = "px-1"><i class="fas fa-dog"></i></span><span class = "px-1"><i class="fas fa-cat"></i></span><span class = "px-1"><i class="fas fa-bone"></i></span>
 </div>
 </div>
 </div>

<br><br><br><br><br><br><br>
<%= link_to "ログイン",new_end_user_session_path, class:"btn btn-dark btn-lg btn-block" %>
<%= link_to "新規登録",new_end_user_registration_path, class:"btn btn-primary btn-lg btn-block mb-3" %>