config/routes.rb
Rails.application.routes.draw do
  devise_for :end_users
  
  root to:'homes#top'
  get 'about', to:'homes#about'
  get 'info', to:'homes#info'
  
  resources:genre,only:[:index,:create,:edit,:update,:destroy]
  resources:type,only:[:index,:create,:edit,:update,:destroy]
  resources:record
  resources:food
  resources:pet
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="UTF-8" />
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': "reload" %>
    <title>ウチの子</title>
  </head>

  <body class="d-flex flex-column vh-100">
      
   <nav class="navbar navbar-expand-lg navbar-light py-3 shadow">
   <div class="container-fluid">
    <div class = "mx-3"> 
     <a class="navbar-brand" href="/">
      <%= image_tag('logo_transparent.png') %>
     </a>
    </div>
  <div class = "mr-3">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" 
                 aria-label="Toggle navigation"> 
   <span class="navbar-toggler-icon"></span>
  </button>
  </div>
  <div class="collapse navbar-collapse ml-3 mt-2" id="navbarNav">
   <ul class="navbar-nav ml-auto">
    <% if end_user_signed_in? %>
     <li class="nav-item">
      <%= link_to pet_index_path, class:'nav-link text-dark' do %>
       <i class="fas fa-paw"></i>
        ウチの子
      <% end %>
     </li>
     <li class="nav-item">
      <%= link_to record_index_path, class:'nav-link text-dark' do %>
       <i class="fas fa-pen"></i>
       記録
      <% end %>
     </li>
     <li class="nav-item">
      <%= link_to food_index_path, class:'nav-link text-dark' do %>
       <i class="fas fa-bone"></i>
       フード
      <% end %>
     </li>
     <li class="nav-item">
      <%= link_to destroy_end_user_session_path, method: :delete, class:'nav-link text-dark' do %>
       <i class="fas fa-sign-out-alt"></i>
       ログアウト
      <% end %>
     </li>
    <% else %>
     <li class="nav-item">
      <%= link_to root_path, class:'nav-link text-dark' do %>
       <i class="fas fa-home"></i>
       ホーム
      <% end %> 
     </li>
     <li class="nav-item">
      <%= link_to new_end_user_session_path, class:'nav-link text-dark' do %>
       <i class="fas fa-sign-in-alt"></i>
       ログイン
      <% end %>
     </li>
     <li class="nav-item">
      <%= link_to new_end_user_registration_path, class:'nav-link text-dark' do %>
       <i class="fas fa-user-plus"></i>
       新規登録
      <% end %>
     </li>
    <% end %>
      </ul>
     </div>
    </div>
   </nav>

  <main>
   <%= link_to about_path, class:"h4 text-reset" do %>
    <div class = "text-right mr-3 mt-2"><i class="fas fa-cog"></i>
    </div>
   <% end %>
 
   <div class="container-lg">
    <div class="notice"><%= notice %></div>
    <div class="alert"><%= alert %></div>
 
   <%= yield %>
   </div>
   
  </main>
  
 </body>

</html>